// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace Projekat.Migrations
{
    [DbContext(typeof(PicerijaContext))]
    partial class PicerijaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Picerija", b =>
                {
                    b.Property<int>("IDPicerije")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Adresa");

                    b.Property<int>("KapacitetPicerije")
                        .HasColumnType("int")
                        .HasColumnName("Kapacitet");

                    b.Property<string>("Naziv")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Naziv");

                    b.HasKey("IDPicerije");

                    b.ToTable("Picerija");
                });

            modelBuilder.Entity("Models.Porudzbina", b =>
                {
                    b.Property<int>("IDPorudzine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Jelovnik")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Jelovnik");

                    b.Property<string>("Napici")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Napici");

                    b.Property<int?>("PicerijaIDPicerije")
                        .HasColumnType("int");

                    b.HasKey("IDPorudzine");

                    b.HasIndex("PicerijaIDPicerije");

                    b.ToTable("Porudzbina");
                });

            modelBuilder.Entity("Models.Sto", b =>
                {
                    b.Property<int>("IDStola")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojStola")
                        .HasColumnType("int")
                        .HasColumnName("Broj");

                    b.Property<string>("Ime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ime");

                    b.Property<int?>("PicerijaIDPicerije")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Prezime");

                    b.Property<string>("StanjeStola")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Stanje");

                    b.HasKey("IDStola");

                    b.HasIndex("PicerijaIDPicerije");

                    b.ToTable("Sto");
                });

            modelBuilder.Entity("Models.Porudzbina", b =>
                {
                    b.HasOne("Models.Picerija", "Picerija")
                        .WithMany("Porudzbine")
                        .HasForeignKey("PicerijaIDPicerije");

                    b.Navigation("Picerija");
                });

            modelBuilder.Entity("Models.Sto", b =>
                {
                    b.HasOne("Models.Picerija", "Picerija")
                        .WithMany("Stolovi")
                        .HasForeignKey("PicerijaIDPicerije");

                    b.Navigation("Picerija");
                });

            modelBuilder.Entity("Models.Picerija", b =>
                {
                    b.Navigation("Porudzbine");

                    b.Navigation("Stolovi");
                });
#pragma warning restore 612, 618
        }
    }
}
